### PR TITLE
Get __STRICT_ALIGNMENT from machine/endian.h

### PR DESCRIPTION
**Pull request by kinichiro**
Proposal for #602

### CODE REVIEW

**Comment by q66** [comment]
This looks fine to me in principle, there are still some concerns though:

1) according to OpenSSL, this should also be covered for `__s390__` and `__s390x__`
2) they seem to imply, in https://github.com/openssl/openssl/commit/29a546720b6d8ea8b3207f500e3ed9d2834b09f2, that it's not actually safe to enable for ARMv7. However, defining `__STRICT_ALIGNMENT` for ARMv7 in LibreSSL would result in the assembly implementation of `ghash` getting disabled. OpenSSL doesn't have a restriction like that in place for `ghash` assembly (they have a much newer version though), and they define the macro for all 32-bit ARM. According to your mentioned OpenBSD commit, LibreSSL upstream also had the macro enabled for all 32-bit ARM.

Also, if you add this, you might want to drop the special case for SPARC from the `configure.ac` script, as it becomes redundant.

**Comment by kinichiro** [comment]
Thanks for seeing this PR and for your comments.
I added one commit.

1. I added arch macro for s390/s390x
2. I think it is the point that give difficulties about ARM with alignment issue.
   v6 and above has some kind of unaligned access support, but there seems to be some conditions ...
   This architecture checks in <machine/endian.h> should be changed according to the progress of ARM.
   Do you have any concrete recommendations for this check, now ?

I also removed redundant sparc check from configure.ac.

**Comment by q66** [comment]
I guess I'd leave it as it is in your PR right now, to match the original intent of the previous code (as `BSWAP4` is defined for ARMv7 without `__STRICT_ALIGNMENT`) and it can perhaps be changed later if the assembly code gets updated

**Comment by kinichiro** [comment]
@q66 Thanks for your feedback.

**Comment by q66** [comment]
Found another thing: `crypto/gost/gost2814789.c` should `#include <machine/endian.h>`, otherwise it will not pick up the macro - I inspected other files as well and this is the only instance where the include is missing

**Comment by q66** [comment]
There is one more thing that came to mind. The `__STRICT_ALIGNMENT` macro is used by some of the ARM `.S` files. That means if we move the macro definition into `endian.h`, it will not get picked up

**Comment by kinichiro** [comment]
I think gost2814789.c should include <machine/endian.h>.

Currently \*armv4\*.S files seem to get \_\_STRICT_ALIGNMENT from arm_arch.h,
and it defines \_\_STRICT_ALIGNMENT when \_\_OpenBSD__ is defined.

**Comment by busterb** [comment]
With the latest gost fixes, is this ready to merge @kinichiro ?

**Comment by kinichiro** [comment]
@busterb I didn't get ok for gost diff yet. I will try again.

**Comment by kinichiro** [comment]
@busterb I had committed gost fix. I think this is ready to merge.

**Pull request merged**
