### PR TITLE
Add x509_verify.c x509_verify.h

### PR DESCRIPTION
**Pull request by kinichiro**
This PR is
- Add x509_verify.c x509_verify.h
- Restrict cipherstest with static build only in CMake, since it changes to use internal function
- Add regress x509_info.c
- Update .gitignore for some files in tests

### CODE REVIEW

**Comment by kinichiro** [comment]
Some regress getting fails

on Windows
- cipherstest (Failed)
- cmstest (SEGFAULT)
- ssltest (Failed)
- tlstest (Failed)

on arm32 and arm64
- cipherstest

OSX, Linux, Android seems fine.
Need investigation.

**Comment by busterb** [comment]
for arm and aaarch64 cipherstest failures (I haven't looked at the Windows ones yet)

```
FAIL: test 0 - got cipher 0 with id 3001303, want 3001302
FAIL cipherstest (exit status: 1)
```

**Comment by busterb** [comment]
For more context, it's failing in `cipher_set_test`

Removing the `goto failed`, we can see that the ciphers are being returned in a different order than expected by the test on arm/aarch64 (though this may be expected by the library):

```
FAIL: test 0 - got cipher 0 with id 3001303, want 3001302
FAIL: test 0 - got cipher 1 with id 3001302, want 3001303
FAIL: test 1 - got cipher 0 with id 3001303, want 3001302
FAIL: test 1 - got cipher 1 with id 3001302, want 3001303
```

**Comment by busterb** [comment]
I think I'll land this PR for now, since it is correct on its own. The other issues should be addressed separately.

**Comment by kinichiro** [comment]
Thanks! It helps to work for now.

**Pull request merged**
