### PR TITLE
Windows build fixes

### PR DESCRIPTION
**Pull request by busterb**
This pulls in changes from #525 moves forward additional build fixes.

### CODE REVIEW

**Comment by kinichiro** [comment]
It seems that '#'(for comments), '|', '~' and '<<' are treated as invalid with MASM.
After replacing these operators, compilation was completed.
See this commit. https://github.com/kinichiro/portable/commit/75d1b7223f79134d126b9cad6e45f7511c93925b

I'm not sure this sed replacing is the best way to solve this ...

commit above modifies below, too.
- To judge adding `-DOPENSSL_NO_ASM` or not, using `CMAKE_GENERATOR` instead `CMAKE_SYSTEM_PROCESSOR`.
- To avoid "cannot open file : Files/LibreSSL/etc/ssl", added `-DCMAKE_INSTALL_PREFIX`.

**Comment by kinichiro** [comment]
Sorry, last commit breaks travis build, and here is fix.
https://github.com/kinichiro/portable/commit/92b366d81deed9cec8d717ad58e7331781f8f440

**Comment by feliwir** [comment]
Do we not want to fix masm working under pathes with whitespaces?

**Comment by busterb** [comment]
Sure @feliwir I saw your note on the other PR. Got a diff?

**Comment by feliwir** [comment]
@busterb no, i think it would be a bigger CMake change, but maybe there's a better solution. We just need to get rid of the `add_definition` here: https://github.com/libressl-portable/portable/blob/master/crypto/CMakeLists.txt#L928 

I can try luck on the weekend on this issue maybe.

**Comment by busterb** [comment]
I think the solution may have been as simple as 83012fe. Giving it a test now, but local results are positive.

**Comment by busterb** [comment]
Hah, incremental compile hid a different issue. Hmm!

**Comment by busterb** [comment]
I think I'm going to live with this for now.

**Comment by feliwir** [comment]
So we merge it like this?

**Comment by busterb** [comment]
I think the final revision looks reasonable. Don't want to default to something directly off of c:\, since anyone can create that on Windows if it doesn't already exist, and thus configure arbitrary certificate trusts and such.

**Comment by feliwir** [comment]
I agree. Will there be a release with this feature in the near feature? Would be quite helpful for me, since AES-NI support has been something we need on windows.

**Comment by busterb** [comment]
In the next dev release, sure! I hesitate to enable it in the 2.8.x tree though.

One note, when we enabled similar optimizations on Linux, in many systems the default linker would assume that the stack needed to be executable unless we overrode the behavior. Is there a similar override/check we should make with Microsoft's assembler to avoid inadvertently making the stack executable with libcrypto?

**Comment by feliwir** [comment]
Not sure about that, sorry :-/

**Comment by busterb** [comment]
Should be able to take a look today to verify.

**Comment by busterb** [comment]
Looks fine to me!

(waiting for Cunningham's law to kick in!)

**Comment by kinichiro** [comment]
It is good to me, and I have no idea about more tests on Windows MASM at
this time.

(Anything we couldn't find out will be posted after cutting out the
Release, according to the Murphy's law :)

>

**Pull request merged**
