### PR TITLE
modify cmake to build nc and add cmake uninstall functionality

### PR DESCRIPTION
**Pull request by kinichiro**
This PR provides 2 changes for cmake build.
- add nc build procedure
- add uninstall functionality

I separated this PR in 2 commits for each changes.

### CODE REVIEW

**Comment by busterb** [comment]
Looks good, thanks for the reorganization.

**Comment by busterb** [comment]
I cherry-picked the 'nc' build commit, but left uninstall out for now. I had some trouble testing it that I'm looking into.

**Comment by busterb** [comment]
OK, the problem I had with the uninstall was on my end. I cherry-picked the uninstall bits as well now. Thanks!

**Comment by kinichiro** [comment]
It is good to hear that uninstall bits also worked.
Thanks.

**Pull request closed without merging**
