### PR TITLE
enable scheduled Coverity scan

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by chipitsine** [comment]
please note that Coverity scan requires proper COVERITY_SCAN_TOKEN specified in repo secrets

**Comment by busterb** [comment]
Added the secret and doing a test run. The email might need to be busterb@gmail.com but we'll see if the token is sufficient.

**Comment by chipitsine** [comment]
pull requests cannot access secret tokens

**Comment by chipitsine** [comment]
sure, feel free to change email if needed

**Pull request merged**
