### PR TITLE
Enable regress handshake_table

### PR DESCRIPTION
**Pull request by kinichiro**

### CODE REVIEW

**Comment by botovq** [comment]
@kinichiro could you please rebase to trigger another CI run? If it succeeds, I'll merge.

**Comment by busterb** [comment]
I tested this locally on macOS 10.15 and they worked fine. Let's retest on travis.

**Comment by kinichiro** [comment]
@busterb @botovq Thanks.

**Comment by busterb** [comment]
Note @botovq don't merge things in github directly, they'll get overwritten on the next sync from upstream.

**Comment by botovq** [comment]
@busterb Oh right, I forgot, sorry about that. Thanks for fixing this.

**Pull request merged**
