### PR TITLE
Fix cmake linking libraries

### PR DESCRIPTION
**Pull request by kinichiro**
Tweak platform specific linking libraries in cmake as suggested by issue #446 .

### CODE REVIEW

**Comment by shinchiro** [comment]
The .pc generated doesn't append '-l' before the lib. This is example of pc file generated by cmake

```
#libcrypto pkg-config source file

prefix=/build/install/mingw
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: LibreSSL-libcrypto
Description: LibreSSL cryptography library
Version: 2.8.1
Requires:
Conflicts:
Libs: -L${libdir} -lcrypto
Libs.private:  ws2_32
Cflags: -I${includedir}
```

**Comment by kinichiro** [comment]
I had added another commit to fix Libs.private in .pc files by adding "-l".
Could you check this, please ?

**Comment by shinchiro** [comment]
Looks right 👍 The generated .pc files are similar with what makefile would produce

**Comment by kinichiro** [comment]
Thanks for merging :)

**Pull request merged**
